import { expect, test } from "@playwright/test";
import { ko } from "../../src/lib/i18n/ko";

test("mixer settings survive reload and are applied when audio starts", async ({ page }) => {
  await page.goto("/");
  const mobileMixer = page.getByRole("button", { name: "Mixer", exact: true });
  if (await mobileMixer.isVisible()) await mobileMixer.click();
  const mixer = page.locator("#mixer");
  const volume = mixer.getByRole("slider", { name: "01 트랙 볼륨" });
  await expect(volume).toBeEnabled();
  await volume.focus();
  await page.keyboard.press("ArrowDown");
  await expect(volume).toHaveAttribute("aria-valuenow", "-0.5");
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  const pan = mixer.getByRole("slider", { name: "01 트랙 팬" });
  await pan.focus();
  await page.keyboard.press("Home");
  await expect(pan).toHaveAttribute("aria-valuenow", "-1");
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  const master = mixer.getByRole("slider", { name: ko.mixerMasterVolume, exact: true });
  await master.focus();
  await page.keyboard.press("Home");
  await expect(master).toHaveAttribute("aria-valuenow", "-60");
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  await mixer.getByRole("button", { name: "01 음소거", exact: true }).click();
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  await mixer.getByRole("button", { name: "02 솔로", exact: true }).click();
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  await page.reload();
  if (await mobileMixer.isVisible()) await mobileMixer.click();
  await expect(volume).toHaveAttribute("aria-valuenow", "-0.5");
  await expect(pan).toHaveAttribute("aria-valuenow", "-1");
  await expect(master).toHaveAttribute("aria-valuenow", "-60");
  await expect(mixer.getByRole("button", { name: "01 음소거", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(mixer.getByRole("button", { name: "02 솔로", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "오디오 연결 설정" }).click();
  await page.getByRole("button", { name: "오디오 시작", exact: true }).click();
  await expect(page.getByRole("button", { name: ko.toneStart, exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(mixer.getByRole("status")).toHaveText(ko.mixerReady);
  await expect(mixer.getByRole("meter", { name: `L ${ko.mixerPeak}`, exact: true })).toHaveAttribute("value", "-60");
  await mixer.getByRole("button", { name: "01 음소거", exact: true }).click();
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  await expect(mixer.locator('[data-mix-track="01"]')).toHaveAttribute("data-audible", "false");
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
});

test("mobile mixer can select both banks and shows solos in the hidden bank", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await page.getByRole("button", { name: "Mixer", exact: true }).click();
  const mixer = page.locator("#mixer");
  await mixer.getByRole("button", { name: "Bank 5–8", exact: true }).click();
  await mixer.getByRole("button", { name: "08 솔로", exact: true }).click();
  await expect(page.getByRole("button", { name: /로컬 저장 상태: 이 기기에 저장됨/ })).toBeVisible();
  await mixer.getByRole("button", { name: "Bank 1–4", exact: true }).click();
  await expect(mixer.getByText("솔로 선택 트랙: 08", { exact: true })).toBeVisible();
  await expect(mixer.locator('[data-mix-track="01"]')).toHaveAttribute("data-audible", "false");
  await expect(mixer.getByRole("button", { name: "01 음소거", exact: true })).toBeVisible();
});
